"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

interface Transaction {
  id: string
    type: string
      amount: number
        description: string
          status: string
            created_at: string
            }

            export function TransactionHistory() {
              const [transactions, setTransactions] = useState<Transaction[]>([])
                const [isLoading, setIsLoading] = useState(true)
                  const [error, setError] = useState<string | null>(null)

                    useEffect(() => {
                        // Hardcoded transactions with only amount, date, and time
                            const data = {
                                  transactions: [
                                          {
                                                    id: "1",
                                                              type: "deposit",
                                                                        amount: 98.90,
                                                                                  description: "Manual Transaction",
                                                                                            status: "completed",
                                                                                                      created_at: "2025-08-29T06:55:06Z", // 6:55:06 AM
                                                                                                              },
                                                                                                                      {
                                                                                                                                id: "2",
                                                                                                                                          type: "deposit",
                                                                                                                                                    amount: 300.0,
                                                                                                                                                              description: "Manual Transaction",
                                                                                                                                                                        status: "completed",
                                                                                                                                                                                  created_at: "2025-08-29T07:25:06Z", // +30 mins
                                                                                                                                                                                          },
                                                                                                                                                                                                  {
                                                                                                                                                                                                            id: "3",
                                                                                                                                                                                                                      type: "deposit",
                                                                                                                                                                                                                                amount: 90.0,
                                                                                                                                                                                                                                          description: "Manual Transaction",
                                                                                                                                                                                                                                                    status: "completed",
                                                                                                                                                                                                                                                              created_at: "2025-08-29T07:55:06Z", // +30 mins
                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                    setTransactions(data.transactions)
                                                                                                                                                                                                                                                                                        setIsLoading(false)
                                                                                                                                                                                                                                                                                          }, [])

                                                                                                                                                                                                                                                                                            const getTransactionColor = (type: string) => {
                                                                                                                                                                                                                                                                                                switch (type) {
                                                                                                                                                                                                                                                                                                      case "deposit":
                                                                                                                                                                                                                                                                                                              return "text-green-600"
                                                                                                                                                                                                                                                                                                                    case "withdraw":
                                                                                                                                                                                                                                                                                                                            return "text-blue-600"
                                                                                                                                                                                                                                                                                                                                  case "transfer":
                                                                                                                                                                                                                                                                                                                                          return "text-orange-600"
                                                                                                                                                                                                                                                                                                                                                case "invest":
                                                                                                                                                                                                                                                                                                                                                        return "text-red-600"
                                                                                                                                                                                                                                                                                                                                                              default:
                                                                                                                                                                                                                                                                                                                                                                      return "text-gray-600"
                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                              const getTransactionSign = (type: string) => {
                                                                                                                                                                                                                                                                                                                                                                                  return type === "deposit" ? "+" : "-"
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                      if (isLoading) {
                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                <Card>
                                                                                                                                                                                                                                                                                                                                                                                                        <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                  <CardTitle>Recent Transactions</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                          </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-500">Loading transactions...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <CardTitle>Recent Transactions</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-red-500">Error: {error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <CardTitle>Recent Transactions</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {transactions.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-500">No transactions yet</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {transactions.map((transaction) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={transaction.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="font-medium text-gray-800">{transaction.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {new Date(transaction.created_at).toLocaleDateString("en-US", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        year: "numeric",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              month: "long",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    day: "numeric",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })}{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {new Date(transaction.created_at).toLocaleTimeString("en-US", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hour: "2-digit",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        minute: "2-digit",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              second: "2-digit",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    hour12: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className={`font-bold ${getTransactionColor(transaction.type)}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {getTransactionSign(transaction.type)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {transaction.amount.toLocaleString("en-US", {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: "currency",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                currency: "USD",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-gray-500 capitalize">{transaction.type}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
