"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { motion } from "framer-motion"
import { X } from "lucide-react"

export default function WithdrawForm() {
  const [btcAddress, setBtcAddress] = useState("")
    const [amount, setAmount] = useState("")
      const [showModal, setShowModal] = useState(false)

        const handleWithdraw = (e: React.FormEvent) => {
            e.preventDefault()
                // Instead of processing, show unsuccessful modal
                    setShowModal(true)
                      }

                        return (
                            <div className="bg-white p-6 rounded-2xl shadow-md relative">
                                  {/* Withdrawal Form */}
                                        <form onSubmit={handleWithdraw} className="space-y-4">
                                                <div>
                                                          <label className="block text-gray-700 font-medium mb-1">BTC Address</label>
                                                                    <Input 
                                                                                type="text"
                                                                                            placeholder="Enter BTC address"
                                                                                                        value={btcAddress}
                                                                                                                    onChange={(e) => setBtcAddress(e.target.value)}
                                                                                                                                required
                                                                                                                                          />
                                                                                                                                                  </div>

                                                                                                                                                          <div>
                                                                                                                                                                    <label className="block text-gray-700 font-medium mb-1">Amount</label>
                                                                                                                                                                              <Input 
                                                                                                                                                                                          type="number"
                                                                                                                                                                                                      placeholder="Enter amount"
                                                                                                                                                                                                                  value={amount}
                                                                                                                                                                                                                              onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                    <Button 
                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                        className="w-full bg-gradient-to-r from-red-500 to-red-600 text-white font-semibold py-2 px-4 rounded-lg shadow hover:opacity-90 transition"
                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                          Withdraw
                                                                                                                                                                                                                                                                                                                  </Button>
                                                                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                                                                              {/* Popup Modal */}
                                                                                                                                                                                                                                                                                                                                    {showModal && (
                                                                                                                                                                                                                                                                                                                                            <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
                                                                                                                                                                                                                                                                                                                                                      <motion.div
                                                                                                                                                                                                                                                                                                                                                                  initial={{ scale: 0.8, opacity: 0 }}
                                                                                                                                                                                                                                                                                                                                                                              animate={{ scale: 1, opacity: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                          transition={{ type: "spring", stiffness: 200, damping: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                      className="bg-white rounded-2xl shadow-lg p-6 max-w-md text-center relative"
                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Close Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                        <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => setShowModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="absolute top-3 right-3 text-gray-500 hover:text-gray-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <X size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Animation Icon */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                initial={{ scale: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              animate={{ scale: 1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition={{ type: "spring", stiffness: 200, damping: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="mb-6 text-red-600 text-6xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ❌
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Message */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1 className="text-2xl font-bold mb-2">Withdrawal Unsuccessful</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-gray-600 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  You cannot withdraw at this time because you have not reached your withdrawal limit.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Close Modal Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => setShowModal(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-gradient-to-r from-blue-500 to-blue-600 text-white px-6 py-2 rounded-lg shadow hover:opacity-90 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Close
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
